import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import Navbar from "../components/Navbar";
import "./globals.css";

const font = Roboto_Condensed({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} min-h-screen`}>
        <header>
          <Navbar />
        </header>
        <main className="pt-20 lg:px-40 bg-[#17181c]">{children}</main>
      </body>
    </html>
  );
}
