import type { Dapps } from "./types";

export const comboData: Dapps[] = [
  {
    name: "Inscription",
    category: "Games",
    description: "The First & Fairest Inscription Protocol on COMBO.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/inscription.png",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Legend Games",
    category: "Games",
    description:
      "An omnichain gaming powered by zkBridge, allowing games to utilize the benefits of different blockchain networks seamlessly.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/legend_games.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Tap Fantasy",
    category: "Games",
    description:
      "Combine classic RPG elements with blockchain innovation. Players can mint NFTs, engage in epic battles, and enjoy mini-games within a MMORPG universe.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/tap_fantasy.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Zypher Games",
    category: "Games",
    description:
      "Fully on-chain games utilizing Zero-Knowledge Proofs and AI technology, set to debut zBingo and 2048 on COMBO soon.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/zypher_games.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "HeroesBattlearn",
    category: "Games",
    description:
      "A free, play & fun multichain game inspired by the legendary 'Heroes Might and Magic', featuring AI, cash rewards & NFTs through strategic battles or lucky draws.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/heroes_battlearn.png",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Arena of Faith",
    category: "Games",
    description:
      "A MOBA game set on the battlefield of Vigrid, where players engage in on-chain eSports, enjoy cross-platform competition, and win various in-game rewards.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/arena_of_faith.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Dark Forest",
    category: "Games",
    description:
      "Based on The Three-Body Problem, this grand FOC game involves a space adventure using zero-knowledge-proof technology.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/dark_forest.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "MetaLine",
    category: "Games",
    description:
      "A web3 multiplayer sailing game that defies geographical and temporal limits, offering players generous token rewards during gameplay.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/metaline.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "DystoWorld",
    category: "Games",
    description:
      "A multi-faceted ecosystem for bringing digital goods to Web3 & the Metaverse. Games, art, computer code, and licenses, all benefit from the true ownership granted by NFTs.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/dystoworld.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Climbers",
    category: "Games",
    description:
      "A universally accessible game playable on smartphones and PC browsers, even without the need for a wallet.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/climbers.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Apes Planet",
    category: "Games",
    description:
      "An innovative spatial computing metaverse that bridges the gap between Unreal Engine 3D Indie Developers and enthusiastic users.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/apes_planet.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "SailWars",
    category: "Games",
    description:
      "A Web3 NFT game that immerses players in a naval battle adventure on the high seas, independently crafted by the experienced Dot.Gaming Studio.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/sailwars.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "SecondLive",
    category: "Games",
    description:
      "Top Metaverse on multichain and server as an all-in-one Web3 metaverse marketing hub with AIGC toolchain and XR technology.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/secondlive.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Math Wallet",
    category: "Wallet",
    description:
      "A multi-platform (mobile/desktop/hardware) universal crypto wallet that enables token storage of 150+ chains.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/MathWallet.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "MetaMask",
    category: "Wallet",
    description:
      "The world’s leading self-custodial wallet. The safe and simple way to access blockchain applications and web3.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/metamask.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Coin98 Super Wallet",
    category: "Wallet",
    description:
      "The leading crypto wallet designed to seamlessly connect a billion users to the crypto world safely and securely.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/coin98.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Safe",
    category: "Wallet",
    description:
      "The account abstraction leader on Ethereum and the EVM with the most secure smart wallet infrastructure and platform.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/safe.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "COMBO Bridge",
    category: "Bridge",
    description: "Transfer BNB, USDT, COMBO and other tokens from.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/combo_bridge.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "ZK Bridge",
    category: "Interoperability",
    description: "Build a fully trustless, efficient, and secure foundation of Web3 interoperability with zkBridge.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/zk_bridge.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "HunterSwap",
    category: "AMM & DEX",
    description: "The first AMM & DEX on COMBO.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/hunterswap.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "HavenMarket",
    category: "Marketplace",
    description: "The first NFT marketplace on COMBO that supports the creation, collection, and trading of NFTs.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/havenmarket.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "NodeReal",
    category: "Infrastructure",
    description:
      "The leading blockchain infrastructure provider offers top-tier RPC services and archive node solutions.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/nodreal.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Polyhedra Network",
    category: "Interoperability",
    description:
      "Develop and implement zkBridge for establishing trustless and highly efficient interoperability infrastructure among diverse Web3 systems.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/polyhedra.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Particle Network",
    category: "Infrastructure",
    description:
      "Full-stack Web3 infrastructure provider offers MPC-TSS Wallet (EOA) and ERC-4337 compatible contract wallet (AA) through Wallet Services.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/particle_network.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "QuestN",
    category: "Marketing",
    description: "Marketing, growth and analysis for Web3.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/questN.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Biconomy",
    category: "Infrastructure",
    description: "Build seamless dApps with Account Abstraction, powered by Biconomy SDK.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/biconomy.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Footprint Analytics",
    category: "Analytics",
    description:
      "Index and structure a wide range of datasets, making it easy to explore data and build next-generation applications whenever required.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/footprint_analytics.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
  {
    name: "Script Network",
    category: "Entertainment",
    description: "A layer 1 open-source live TV platform, protocol, and storage network.",
    website: "",
    logo: "https://combonetwork.io/images/allapps/script_network.svg",
    tags: [],
    dailyUsers: 0,
    dailyTxns: 0,
    chainName: "combo",
  },
];
